@echo off
cd /d %~dp0
..\Png2Cloud.exe ../../ICL_NUIM_living_room/sandbox_2/depth/ ../../ICL_NUIM_living_room/sandbox_2/color/ ../../ICL_NUIM_living_room/sandbox_2/camera_para.txt ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_xyzn/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds_xyzn/
..\Sift.exe ../../ICL_NUIM_living_room/sandbox_2/color/ ../../ICL_NUIM_living_room/sandbox_2/sift_correspondence.txt
..\ShiTomasi.exe ../../ICL_NUIM_living_room/sandbox_2/color/ ../../ICL_NUIM_living_room/sandbox_2/corner_correspondence.txt
..\Narf.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud_xyzn/ ../../ICL_NUIM_living_room/sandbox_2/keypoint/ ../../ICL_NUIM_living_room/sandbox_2/geometric_descriptor/
::SIFT matching
..\ColorCorrespondence.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds/ ../../ICL_NUIM_living_room/sandbox_2/depth/ ../../ICL_NUIM_living_room/sandbox_2/sift_correspondence.txt ../../ICL_NUIM_living_room/sandbox_2/camera_para.txt -4.0 ../../ICL_NUIM_living_room/sandbox_2/sift_traj.txt ../../ICL_NUIM_living_room/sandbox_2/sift_info.txt
::ShiTomasi matching
..\ColorCorrespondence.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds/ ../../ICL_NUIM_living_room/sandbox_2/depth/ ../../ICL_NUIM_living_room/sandbox_2/corner_correspondence.txt ../../ICL_NUIM_living_room/sandbox_2/camera_para.txt -4.0 ../../ICL_NUIM_living_room/sandbox_2/corner_traj.txt ../../ICL_NUIM_living_room/sandbox_2/corner_info.txt
..\GeometricCorrespondence.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds/ ../../ICL_NUIM_living_room/sandbox_2/keypoint/ ../../ICL_NUIM_living_room/sandbox_2/geometric_descriptor/ ../../ICL_NUIM_living_room/sandbox_2/camera_para.txt -4.0 ../../ICL_NUIM_living_room/sandbox_2/narf_traj.txt ../../ICL_NUIM_living_room/sandbox_2/narf_info.txt
..\MergeInfo.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud_ds/ ../../ICL_NUIM_living_room/sandbox_2/narf_traj.txt ../../ICL_NUIM_living_room/sandbox_2/narf_info.txt ../../ICL_NUIM_living_room/sandbox_2/sift_traj.txt ../../ICL_NUIM_living_room/sandbox_2/sift_info.txt ../../ICL_NUIM_living_room/sandbox_2/corner_traj.txt ../../ICL_NUIM_living_room/sandbox_2/corner_info.txt ../../ICL_NUIM_living_room/sandbox_2/traj.txt ../../ICL_NUIM_living_room/sandbox_2/info.txt
..\GlobalOptimizer1.exe ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/traj.txt ../../ICL_NUIM_living_room/sandbox_2/info.txt ../../ICL_NUIM_living_room/sandbox_2/pose_opt1.txt ../../ICL_NUIM_living_room/sandbox_2/fail_build_complete_model.txt ../../ICL_NUIM_living_room/sandbox_2/selected_edge_opt1.txt 0.35 0.55 0.35 0.001
if exist ../../ICL_NUIM_living_room/sandbox_2/fail_build_complete_model.txt goto OVER
..\GlobalOptimizer2.exe ../../ICL_NUIM_living_room/sandbox_2/pose_opt1.txt ../../ICL_NUIM_living_room/sandbox_2/pointcloud/ ../../ICL_NUIM_living_room/sandbox_2/traj.txt ../../ICL_NUIM_living_room/sandbox_2/info.txt ../../ICL_NUIM_living_room/sandbox_2/pose_opt2.txt ../../ICL_NUIM_living_room/sandbox_2/traj_remain_opt2.txt ../../ICL_NUIM_living_room/sandbox_2/info_remain_opt2.txt 50.0
:OVER